- task: AzureFunctionApp@2
  inputs:
    azureSubscription: 'Pay-As-You-Go (0aa88b35-0b03-4473-baff-76cb88734c70)'
    appType: 'functionApp'
    appName: 'FHLBCIN'
    deployToSlotOrASE: true
    resourceGroupName: 'FHLBC'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'